const WORKSHOPS_LIST_LOADING = 'WORKSHOPS_LIST_LOADING';
const WORKSHOPS_LIST_ERROR_LOADING = 'WORKSHOPS_LIST_ERROR_LOADING';
const WORKSHOPS_LIST_LOADED = 'WORKSHOPS_LIST_LOADED';

export {
    WORKSHOPS_LIST_LOADING,
    WORKSHOPS_LIST_ERROR_LOADING,
    WORKSHOPS_LIST_LOADED
};