const WORKSHOPS_LIST_LOADING = 'WORKSHOPS_LIST_LOADING'
const  WORKSHOPS_LIST_LOADED = 'WORKSHOPS_LIST_LOADED'
const  WORKSHOPS_LIST_ERROR_LOADING = 'WORKSHOPS_LIST_ERROR_LOADING'

export{
    WORKSHOPS_LIST_ERROR_LOADING,
    WORKSHOPS_LIST_LOADING,
    WORKSHOPS_LIST_LOADED
}