import React from 'react';
import ReactDOM from 'react-dom';
// import CounterContainer from './containers/CounterContainer'
import CounterContainer from './containers/CounterContainer-autogenerated-from-connect'
//import FormContainer from './containers/FormContainer'
import FormContainer from './containers/FormContainer-autogen-connect'
import {Provider} from 'react-redux'
import store from './store'
ReactDOM.render(
  <React.StrictMode>
    {/*  Provider  makes my store available to all the component inside it  */}
    <Provider store= {store}> 
      <CounterContainer />
      <FormContainer />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals

