a1=("\t\t\t___\n\t\t\t|")
a2=("\t\t\t___\n\t\t\t|\n\t\t\t0")
a3=("\t\t\t___\n\t\t\t|\n\t\t\t0\n\t\t        |")
a4=("\t\t\t___\n\t\t\t|\n\t\t\t0\n\t\t       /|")
a5=("\t\t\t___\n\t\t\t|\n\t\t\t0\n\t\t       /|\ ")
a6=("\t\t\t___\n\t\t\t|\n\t\t\t0\n\t\t       /|\ \n\t\t       /")
a7=("\t\t\t___\n\t\t\t|  |\n\t\t\t0  |\n\t\t       /|\ | \n\t\t       / \ | ")
print(a1)
print(a5)